apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-server-with-custom-ca
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: workload-server-with-custom-ca
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: workload-server-with-custom-ca
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: workload-server-with-custom-ca
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: workload-server-with-custom-ca
      conventions.carto.run/framework: spring-boot
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/version: 2.3.2.RELEASE
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          multi-purpose-convention/x95castle1.org-readiness
          multi-purpose-convention/x95castle1.org-liveness
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        x95castle1.org/livenessProbe: '{"httpGet":{"path": "/actuator/health","port":8080},"initialDelaySeconds": 25,"periodSeconds": 5}'
        x95castle1.org/readinessProbe: '{"httpGet":{"path": "/actuator/health","port":8080},"initialDelaySeconds": 25,"periodSeconds": 5}'
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: workload-server-with-custom-ca
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: workload-server-with-custom-ca
        conventions.carto.run/framework: spring-boot
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: cxscssa.azurecr.io/tap-build/workloads/workload-server-with-custom-ca-jeremy@sha256:716561cd10ae0867fd40a4699fbd410ea238209ae9e10b111e72570306372ac8
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 5
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 5
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: workload-server-with-custom-ca
  labels:
    app.kubernetes.io/part-of: workload-server-with-custom-ca
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: workload-server-with-custom-ca
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: workload-server-with-custom-ca
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: workload-server-with-custom-ca
    conventions.carto.run/framework: spring-boot
  ports:
  - targetPort: 8080
    port: 8080
    name: http

