apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: java-rest-service-aws
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: java-rest-service-aws
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    backstage.io/kubernetes-id: customer-profile
    app.kubernetes.io/component: run
    carto.run/workload-name: java-rest-service-aws
spec:
  type: openapi
  description: Manage customer profiles
  system: profile-management-azure
  owner: customer-relations-department-azure
  location:
    apiSpec:
      path: /api-docs
    server:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: java-rest-service-aws

