apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: workload-web-with-custom-ca-workload-web-with-custom-ca
  annotations:
    autoscaling.knative.dev/minScale: "1"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: workload-web-with-custom-ca
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: workload-web-with-custom-ca
spec:
  name: workload-web-with-custom-ca
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: workload-web-with-custom-ca
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: workload-web-with-custom-ca
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: workload-web-with-custom-ca-ca-cert
  annotations:
    autoscaling.knative.dev/minScale: "1"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: workload-web-with-custom-ca
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: workload-web-with-custom-ca
spec:
  name: ca-cert
  service:
    apiVersion: v1
    kind: Secret
    name: tap-ca
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: workload-web-with-custom-ca

